BEGIN;

-- Add soft delete and active status columns to location tables if not exists
ALTER TABLE states ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE NULL;
ALTER TABLE states ADD COLUMN IF NOT EXISTS is_active SMALLINT DEFAULT 1;
ALTER TABLE states ADD COLUMN IF NOT EXISTS is_deleted SMALLINT DEFAULT 0;

ALTER TABLE districts ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE NULL;
ALTER TABLE districts ADD COLUMN IF NOT EXISTS is_active SMALLINT DEFAULT 1;
ALTER TABLE districts ADD COLUMN IF NOT EXISTS is_deleted SMALLINT DEFAULT 0;

ALTER TABLE cities ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP WITH TIME ZONE NULL;
ALTER TABLE cities ADD COLUMN IF NOT EXISTS is_active SMALLINT DEFAULT 1;
ALTER TABLE cities ADD COLUMN IF NOT EXISTS is_deleted SMALLINT DEFAULT 0;

COMMIT;
