export * from "./constants/product.constants.js";
export * from "./interfaces/product.interface.js";
export * from "./dto/product.dto.js";
export * from "./validators/product.validator.js";
export * from "./repositories/product.repository.js";
export * from "./services/product.service.js";
export * from "./controllers/product.controller.js";
import productRoutes from "./routes/product.routes.js";
export { productRoutes };
