export const USER_MESSAGES = {
    FETCHED_SUCCESS: "Users fetched successfully",
    FETCHED_ALL_SUCCESS: "All users fetched successfully",
    FETCHED_ONE_SUCCESS: "User fetched successfully",
    CREATED_SUCCESS: "User created successfully",
    UPDATED_SUCCESS: "User updated successfully",
    DELETED_SUCCESS: "User deleted successfully",
    RESTORED_SUCCESS: "User restored successfully",
    NOT_FOUND: "User not found",
    ALREADY_EXISTS: "User with this email already exists",
    SYSTEM_USER_UPDATE_ERROR: "System users cannot be modified",
    SYSTEM_USER_DELETE_ERROR: "System users cannot be deleted",
    UPDATE_FAILED: "Failed to update user",
    DELETE_FAILED: "Failed to delete user",
    RESTORE_FAILED: "Failed to restore user or user not found in deleted state",
    UPDATE_NO_FIELDS: "At least one field must be provided to update",
    VALIDATION_ERROR: "Validation Error",
    INVALID_UID: "Invalid user UID",
    INVALID_ROLE_UID: "Invalid role UID",
    FIRST_NAME_MIN_LENGTH: "First name must be at least 2 characters",
    FIRST_NAME_MAX_LENGTH: "First name must be at most 100 characters",
    LAST_NAME_MIN_LENGTH: "Last name must be at least 2 characters",
    LAST_NAME_MAX_LENGTH: "Last name must be at most 100 characters",
    INVALID_EMAIL: "Invalid email format",
    PASSWORD_MIN_LENGTH: "Password must be at least 8 characters",
} as const;
