export const ROLE_MESSAGES = {
    FETCHED_SUCCESS: "Roles fetched successfully",
    FETCHED_ALL_SUCCESS: "All roles fetched successfully",
    FETCHED_ONE_SUCCESS: "Role fetched successfully",
    CREATED_SUCCESS: "Role created successfully",
    UPDATED_SUCCESS: "Role updated successfully",
    DELETED_SUCCESS: "Role deleted successfully",
    RESTORED_SUCCESS: "Role restored successfully",
    NOT_FOUND: "Role not found",
    ALREADY_EXISTS: "Role with this name already exists",
    SYSTEM_ROLE_UPDATE_ERROR: "System roles cannot be modified",
    SYSTEM_ROLE_DELETE_ERROR: "System roles cannot be deleted",
    UPDATE_FAILED: "Failed to update role",
    DELETE_FAILED: "Failed to delete role",
    RESTORE_FAILED: "Failed to restore role or role not found in deleted state",
    UPDATE_NO_FIELDS: "At least one field must be provided to update",
    VALIDATION_ERROR: "Validation Error",
    INVALID_UID: "Invalid role UID",
    NAME_MIN_LENGTH: "Name must be at least 2 characters",
    NAME_MAX_LENGTH: "Name must be at most 100 characters",
    DESCRIPTION_MAX_LENGTH: "Description must be at most 500 characters",
} as const;
